// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX3O9EoE-TMTLGeBoJ87JJoqePuN1TUFs',
    appId: '1:655950008164:web:8db71c9be4b2bfd8617471',
    messagingSenderId: '655950008164',
    projectId: 'appwork-9d729',
    authDomain: 'appwork-9d729.firebaseapp.com',
    storageBucket: 'appwork-9d729.firebasestorage.app',
    measurementId: 'G-6W52P8S56B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtDf5eMQtfyxmgc7noWIoFe8-_KqU67cY',
    appId: '1:655950008164:android:576db3f3db6a4ed2617471',
    messagingSenderId: '655950008164',
    projectId: 'appwork-9d729',
    storageBucket: 'appwork-9d729.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ9sOmnjvB8_MwfP8rp-1AAzfxO0eLt3k',
    appId: '1:655950008164:ios:57ad7ae1155c8ed3617471',
    messagingSenderId: '655950008164',
    projectId: 'appwork-9d729',
    storageBucket: 'appwork-9d729.firebasestorage.app',
    iosBundleId: 'com.example.appdev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ9sOmnjvB8_MwfP8rp-1AAzfxO0eLt3k',
    appId: '1:655950008164:ios:57ad7ae1155c8ed3617471',
    messagingSenderId: '655950008164',
    projectId: 'appwork-9d729',
    storageBucket: 'appwork-9d729.firebasestorage.app',
    iosBundleId: 'com.example.appdev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX3O9EoE-TMTLGeBoJ87JJoqePuN1TUFs',
    appId: '1:655950008164:web:9e9308f303802b1a617471',
    messagingSenderId: '655950008164',
    projectId: 'appwork-9d729',
    authDomain: 'appwork-9d729.firebaseapp.com',
    storageBucket: 'appwork-9d729.firebasestorage.app',
    measurementId: 'G-RX4GCQES2Z',
  );
}
